### ISSUE TITLE
that is for linux or can run at windows?

### ISSUE THREAD

**Issue by felipetmartini** [e00dan/node-server-manager#2]
and what features have and for what plataform??

**Comment by e00dan** [comment]
You can run it on any platform [node.js](http://nodejs.org/) runs on, so it runs on Windows, Linux and Macintosh.
Features are:
- Get Server Status(is online, uptime, etc.)
- Get Players Online(get online players list with names and levels)

**Comment by felipetmartini** [comment]
but only get functions or can kick players and rerstar server or other things?

**Comment by e00dan** [comment]
No, it's different thing.

**Comment by felipetmartini** [comment]
hmm sorry but i dont understand as well, for what this is good?

**Comment by e00dan** [comment]
It could be good in future if I would add more complex communication layer etc. For now, it's just unique attempt to wrap TFS socket communication in node.js.
